TOP=../..
include $(TOP)/configure/CONFIG

#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of DB files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
#  Creation of <name>.dbd file from <name>Include.dbd
#DBDNAME += HP53181A.dbd
#----------------------------------------------------
# Add databases, templates, substitutions like this
DB += Hp53181A.db
DB += Hp53181ASet.db
DB += Hp53181ATest.db

#----------------------------------------------------
# Declare template files which do not show up in DB
#USES_TEMPLATE += HP53181A.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
