TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DBD += devHp53181AGpib.dbd

LIBRARY_IOC = devHp53181AGpib

devHp53181AGpib_SRCS    += devHp53181AGpib.c

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

